<?php

// ~/root/backend/routes/web.php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// 1. The Smart Root Route
Route::get('/', function () {
    // If the user is already logged in, send them to the dashboard
    if (Auth::check()) {
        return redirect('/home');
    }
    // Otherwise, send them to the login page
    return redirect('/login');
});

// 2. The Auth Routes (Generated by Laravel UI)
// This creates /login, /register, /password/reset, etc.
Auth::routes();

// 3. The Dashboard Route
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Group all Admin routes together
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {

    // User Management Routes
    Route::get('/users', [UserController::class, 'index'])->name('users.index');

    // Later we will add: create, store, edit, update, destroy...
});
